### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by PhychicNinja** [Superjo149/Modded-minecraft-servers#2]
when in chrome on 100% zoom top buttons are off screen apart from home
![scroll](https://cloud.githubusercontent.com/assets/10683949/5891552/70e02980-a4e8-11e4-8b3c-48df6cdc90a9.PNG)

![normal](https://cloud.githubusercontent.com/assets/10683949/5891553/75b91a48-a4e8-11e4-9abe-6937bf4f144a.PNG)

**Comment by PhychicNinja** [comment]
another issue on edit page, quick jump thing follows and is annoying 
![capture1](https://cloud.githubusercontent.com/assets/10683949/5891586/71dfc438-a4ea-11e4-9f3d-5b5c62bf998a.PNG)
![capture](https://cloud.githubusercontent.com/assets/10683949/5891587/74de5334-a4ea-11e4-89e6-34baaa1fa5b1.PNG)

**Comment by Superjo149** [comment]
These should both be fixed.

**Comment by PhychicNinja** [comment]
Haven't had a chance to get on pc so I checked on phone and I'm not sure if your really want to make it mobile friendly, if so the banner and top buttons are on the left half of the screen almost exactly when on home page, and when in edit page that quick nav bar is pretty much off the screen, and idk if I can add pics from phone so I will in a few hours when I get home from school if you need.

**Comment by Superjo149** [comment]
Mobile friendly is an idea for the near future
