### ISSUE TITLE
My Servers & New Server

### ISSUE THREAD

**Issue by PhychicNinja** [Superjo149/Modded-minecraft-servers#3]
When I go to My Servers the server I previously put up there still shows up but the Edit button isn't there. Also whenever I try to create a new server the screen flashes up then says 2105 in the top corner and nothing else on the rest of the screen.
![capture](https://cloud.githubusercontent.com/assets/10683949/5991617/2c9123ac-aa46-11e4-9a74-e3d084998927.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10683949/5991618/2c96116e-aa46-11e4-91ac-aef342c9575a.PNG)

**Comment by AnodyneEntity** [comment]
I can confirm that this happens.

**Comment by Superjo149** [comment]
@PhychicNinja @AnodyneEntity Could you check if this is still happening?

**Comment by PhychicNinja** [comment]
Now the whole website doesn't open 
![capture](https://cloud.githubusercontent.com/assets/10683949/6312642/bdd68e12-b9cb-11e4-8052-d1d50995d19a.PNG)

**Comment by Superjo149** [comment]
This has been fixed
